### ISSUE TITLE
Error with libcublasLt.so.12 while running B3 model – Could it be related to CUDA version?

### ISSUE THREAD

**Issue by kbfz12** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024#73]
Hi,

I encountered an issue while running the B3 model from your repository. After following the installation instructions (including setting up the conda environment), I ran into the error:

`Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory.`

Could this be related to the CUDA version? Could you please confirm the CUDA version you used for this project? Any guidance on resolving this would be greatly appreciated.

Thanks in advance!

**Comment by pchampio** [comment]
After the installation, cuda with this specific version shoud be installed (https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/blob/main/00_install.sh#L22)
After the installation you should have the following:
```
    ./venv/lib/libcublasLt.so -> libcublasLt.so.11.10.1.25
    ./venv/lib/stubs/libcublasLt.so
    ./venv/lib/libcublasLt.so.11 -> ./libcublasLt.so.11.10.1.25
    ./venv/lib/python3.11/site-packages/torch/lib/libcublasLt.so.11
    ./venv/lib/libcublasLt.so.11.10.1.25
 ```
 Could you re-run the install script ?

**Comment by kbfz12** [comment]
I’ve checked the venv/lib/ folder, and it has the required files that you mentioned. However, I’m still getting the error. It seems like the program is looking for libcublasLt.so.12, even though I have the version 11 library. I’ve re-run the install script three times, but the issue still persists. Could it be due to the version mismatch?

**Comment by kbfz12** [comment]
Actually, I’ve noticed that the same error occurs whenever I try to run any GPU-related tasks in this project. However, when I test torch.cuda.is_available(), it returns True, so the GPU seems to be available. I’ve also tried deleting the entire folder and reinstalling the environment as per the script instructions multiple times, but the issue persists.
Any suggestions on what might be causing this?

**Comment by pchampio** [comment]
In the ./02_run.sh script, could you print the env variables (`env` after `source ./env.sh`) ?

**Comment by pchampio** [comment]
> Any suggestions on what might be causing this?

I think this is maybe a problem with the virtual env not been picked up, but rather a system one.
PATH, LD_LIBRARY_PATH might not be valid.

Maybe change the first line of `./02_run.sh` from `#!/bin/bash` to `#!/usr/bin/env bash`

**Comment by pchampio** [comment]
Also, your pytorch installation might be wrong.
Could you print `import torch; print(torch.__version__); print(torch.__path__)` from the `./02_run.sh` script (again after the `source ./env.sh`)

Did you modify the `PYTHONPATH` ?

**Comment by pchampio** [comment]
Does this error occurs with the B5/B4 baselines?
And could you provide the full stack-trace.

**Comment by kbfz12** [comment]
The same error occurs with B4 and B5 baselines.
Here’s the stack trace:
`(/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv) [myname@game Voice-Privacy-Challenge-2024]$ ./02_run.sh configs/anon_sttts.yaml 2,3
AUTOJUMP_ERROR_PATH=/home/2023/myname/.local/share/autojump/errors.log
XDG_SESSION_ID=914
HOSTNAME=game
SELINUX_ROLE_REQUESTED=
PIP_REQUIRE_VIRTUALENV=false
AUTOJUMP_SOURCED=1
SHELL=/bin/bash
TERM=screen
HISTSIZE=1000
SSH_CLIENT=10.10.10.7 32820 22
TMPDIR=/Work21/2023/myname/test_tmp/
CONDA_SHLVL=2
CONDA_PROMPT_MODIFIER=(/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv) 
SELINUX_USE_CURRENT_RANGE=
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
SSH_TTY=/dev/pts/10
USER=myname
http_proxy=172.23.166.229:7897
LD_LIBRARY_PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/:/Work21/2023/myname/anaconda3/envs/dataspeech/lib:/usr/local/cuda/lib64
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
CONDA_EXE=/Work21/2023/myname/anaconda3/bin/conda
CUDAROOT=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
TMUX=/Work21/2023/myname/test_tmp/tmux-43268/default,133149,0
_CE_CONDA=
CONDA_PREFIX_1=/Work21/2023/myname/anaconda3
MAIL=/var/spool/mail/myname
PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/bin:/Work21/2023/myname/git-2.44.0/bin:/Work21/2023/myname/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/2023/myname/.local/bin:/home/2023/myname/bin:/home/2023/myname/.local/bin:/home/2023/myname/bin
GSETTINGS_SCHEMA_DIR=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/share/glib-2.0/schemas
XML_CATALOG_FILES=file:///Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/etc/xml/catalog file:///etc/xml/catalog
CONDA_PREFIX=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
PWD=/Work21/2023/myname/Voice-Privacy-Challenge-2024
LANG=en_US.UTF-8
TMUX_PANE=%0
SELINUX_LEVEL_REQUESTED=
https_proxy=172.23.166.229:7897
HISTCONTROL=ignoredups
_CE_M=
HOME=/home/2023/myname
SHLVL=3
XDG_CACHE_HOME=/Work21/2023/myname/cache/
CONDA_PYTHON_EXE=/Work21/2023/myname/anaconda3/bin/python
LOGNAME=myname
SSH_CONNECTION=10.10.10.7 32820 10.10.10.41 22
CONDA_DEFAULT_ENV=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/43268
_=/usr/bin/env
Testing CUDA, cuDNN, and PyTorch...
CUDA is available.
CUDA version: 11.7
cuDNN is available.
cuDNN version: 8902
PyTorch version: 2.0.1+cu117
Using GPU: NVIDIA GeForce RTX 3090
Tensor on GPU: tensor([1., 2., 3.], device='cuda:0')
Testing completed.
Using config: configs/anon_sttts.yaml
Using GPUs: 2,3
2024-12-10 05:25:15,972 - __main__- INFO - Running pipeline: sttts
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
./02_run.sh: line 50: 153589 Aborted                 python run_anonymization.py --config ${anon_config} ${force_compute}`

**Comment by kbfz12** [comment]
The same error occurs with B4 and B5 baselines.
Here’s the stack trace:
```
(/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv) [myname@game Voice-Privacy-Challenge-2024]$ ./02_run.sh configs/anon_sttts.yaml 2,3
AUTOJUMP_ERROR_PATH=/home/2023/myname/.local/share/autojump/errors.log
XDG_SESSION_ID=914
HOSTNAME=game
SELINUX_ROLE_REQUESTED=
PIP_REQUIRE_VIRTUALENV=false
AUTOJUMP_SOURCED=1
SHELL=/bin/bash
TERM=screen
HISTSIZE=1000
SSH_CLIENT=10.10.10.7 32820 22
TMPDIR=/Work21/2023/myname/test_tmp/
CONDA_SHLVL=2
CONDA_PROMPT_MODIFIER=(/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv) 
SELINUX_USE_CURRENT_RANGE=
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
SSH_TTY=/dev/pts/10
USER=myname
http_proxy=172.23.166.229:7897
LD_LIBRARY_PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/:/Work21/2023/myname/anaconda3/envs/dataspeech/lib:/usr/local/cuda/lib64
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
CONDA_EXE=/Work21/2023/myname/anaconda3/bin/conda
CUDAROOT=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
TMUX=/Work21/2023/myname/test_tmp/tmux-43268/default,133149,0
_CE_CONDA=
CONDA_PREFIX_1=/Work21/2023/myname/anaconda3
MAIL=/var/spool/mail/myname
PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/bin:/Work21/2023/myname/git-2.44.0/bin:/Work21/2023/myname/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/2023/myname/.local/bin:/home/2023/myname/bin:/home/2023/myname/.local/bin:/home/2023/myname/bin
GSETTINGS_SCHEMA_DIR=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/share/glib-2.0/schemas
XML_CATALOG_FILES=file:///Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/etc/xml/catalog file:///etc/xml/catalog
CONDA_PREFIX=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
PWD=/Work21/2023/myname/Voice-Privacy-Challenge-2024
LANG=en_US.UTF-8
TMUX_PANE=%0
SELINUX_LEVEL_REQUESTED=
https_proxy=172.23.166.229:7897
HISTCONTROL=ignoredups
_CE_M=
HOME=/home/2023/myname
SHLVL=3
XDG_CACHE_HOME=/Work21/2023/myname/cache/
CONDA_PYTHON_EXE=/Work21/2023/myname/anaconda3/bin/python
LOGNAME=myname
SSH_CONNECTION=10.10.10.7 32820 10.10.10.41 22
CONDA_DEFAULT_ENV=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/43268
_=/usr/bin/env
Testing CUDA, cuDNN, and PyTorch...
CUDA is available.
CUDA version: 11.7
cuDNN is available.
cuDNN version: 8902
PyTorch version: 2.0.1+cu117
Using GPU: NVIDIA GeForce RTX 3090
Tensor on GPU: tensor([1., 2., 3.], device='cuda:0')
Testing completed.
Using config: configs/anon_sttts.yaml
Using GPUs: 2,3
2024-12-10 05:25:15,972 - __main__- INFO - Running pipeline: sttts
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
./02_run.sh: line 50: 153589 Aborted                 python run_anonymization.py --config ${anon_config} ${force_compute}
```
And the./02_run.sh:
```
#!/bin/bash

set -e

source env.sh

env

python test_cuda.py

### Variables

# Select the anonymization pipeline
if [ -n "$1" ]; then
  anon_config=$1
else
  anon_config=configs/anon_mcadams.yaml
  # anon_config=configs/anon_sttts.yaml
  # anon_config=configs/anon_template.yaml
  # anon_config=configs/anon_asrbn.yaml
  # anon_config=configs/anon_nac.yaml
fi
echo "Using config: $anon_config"

force_compute=
force_compute='--force_compute True'

# JSON to modify run_evaluation(s) configs, see below
eval_overwrite="{"

### Check and set GPU:
if [ -n "$2" ]; then
  export CUDA_VISIBLE_DEVICES=$2
  echo "Using GPUs: $CUDA_VISIBLE_DEVICES"
else
  echo "No GPU specified, using default GPUs"
  # Optionally, you can set a default if no GPUs are specified
  # export CUDA_VISIBLE_DEVICES="0,1"  # e.g., use GPU 0 and 1 by default
fi

### Anonymization + Evaluation:

# find the $anon_suffix (data/dataset_$anon_suffix) = to where the anonymization produces the data files
anon_suffix=$(python3 -c "from hyperpyyaml import load_hyperpyyaml; f = open('${anon_config}'); print(load_hyperpyyaml(f, None).get('anon_suffix', ''))")
if [[ $anon_suffix ]]; then
  eval_overwrite="$eval_overwrite \"anon_data_suffix\": \"$anon_suffix\"}"
fi

# Generate anonymized audio (libri dev+test set & IEMOCAP dev+test set & libri-360h)
python run_anonymization.py --config ${anon_config} ${force_compute}

# Perform libri dev+test & IEMOCAP dev+test pre evaluation using pretrained ASR/ASV/SER models
python run_evaluation.py --config $(dirname ${anon_config})/eval_pre.yaml --overwrite "${eval_overwrite}" ${force_compute}

# Train post ASV using anonymized libri-360 and perform libri dev+test post evaluation
# ASV training takes ~2hours
python run_evaluation.py --config $(dirname ${anon_config})/eval_post.yaml --overwrite "${eval_overwrite}" ${force_compute}

# Merge results
results_summary_path_orig=$(python3 -c "from hyperpyyaml import load_hyperpyyaml; f = open('$(dirname ${anon_config})/eval_pre.yaml'); print(load_hyperpyyaml(f, ${eval_overwrite}).get('results_summary_path', ''))")
results_summary_path_anon=$(python3 -c "from hyperpyyaml import load_hyperpyyaml; f = open('$(dirname ${anon_config})/eval_post.yaml'); print(load_hyperpyyaml(f, ${eval_overwrite}).get('results_summary_path', ''))")
[[ "$results_summary_path_anon" == *"_test_tool"* ]] && exit 0

results_exp=exp/results_summary
mkdir -p ${results_exp}
{ cat "${results_summary_path_orig}"; echo; cat "${results_summary_path_anon}"; } > "${results_exp}/result_for_rank${anon_suffix}"
zip ${results_exp}/result_for_submission${anon_suffix}.zip -r exp/asr/*${anon_suffix} exp/asr/*${anon_suffix}.csv exp/ser/*${anon_suffix}.csv exp/results_summary/*${anon_suffix}* exp/asv_orig/*${anon_suffix} exp/asv_orig/*${anon_suffix}.csv exp/asv_anon${anon_suffix} > /dev/null
```
test_cuda.py:
```
import torch

def test_cuda():
    # 检查CUDA是否可用
    if torch.cuda.is_available():
        print("CUDA is available.")
        cuda_version = torch.version.cuda
        print(f"CUDA version: {cuda_version}")
    else:
        print("CUDA is not available.")
        return False

def test_cudnn():
    # 检查cuDNN是否可用
    if torch.backends.cudnn.is_available():
        print("cuDNN is available.")
        cudnn_version = torch.backends.cudnn.version()
        print(f"cuDNN version: {cudnn_version}")
    else:
        print("cuDNN is not available.")
        return False

def test_torch():
    # 检查PyTorch版本
    torch_version = torch.__version__
    print(f"PyTorch version: {torch_version}")

    # 检查GPU是否可以被PyTorch使用
    if torch.cuda.is_available():
        device = torch.device("cuda")
        print(f"Using GPU: {torch.cuda.get_device_name(0)}")
        # 创建一个张量并移动到GPU上
        x = torch.tensor([1.0, 2.0, 3.0]).to(device)
        print(f"Tensor on GPU: {x}")
    else:
        print("GPU is not available for PyTorch.")
        return False

if __name__ == "__main__":
    print("Testing CUDA, cuDNN, and PyTorch...")
    test_cuda()
    test_cudnn()
    test_torch()
    print("Testing completed.")
```

**Comment by pchampio** [comment]
Could you also indicate the `torch.__path__` and version.
See above.


Also, it seems that you have a conda env activated.
Please de-activate your /Work21/2023/myname/anaconda3 env.
We don't support having 2 conda env at once.

**Comment by kbfz12** [comment]
I’ve completely de-activated my conda environment as per your suggestion, but I’m still encountering the same error. Here’s the path and version of PyTorch:

```
PyTorch path: ['/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/python3.11/site-packages/torch']
PyTorch version: 2.0.1+cu117
```
And here’s the stack trace:

```
[myname@game Voice-Privacy-Challenge-2024]$ ./02_run.sh configs/anon_sttts.yaml 2
AUTOJUMP_ERROR_PATH=/home/2023/myname/.local/share/autojump/errors.log
XDG_SESSION_ID=914
HOSTNAME=game
SELINUX_ROLE_REQUESTED=
PIP_REQUIRE_VIRTUALENV=false
AUTOJUMP_SOURCED=1
SHELL=/bin/bash
TERM=screen
HISTSIZE=1000
SSH_CLIENT=10.10.10.7 32820 22
TMPDIR=/Work21/2023/myname/test_tmp/
CONDA_SHLVL=1
CONDA_PROMPT_MODIFIER=(/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv) 
SELINUX_USE_CURRENT_RANGE=
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
SSH_TTY=/dev/pts/10
USER=myname
LD_LIBRARY_PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/:/Work21/2023/myname/anaconda3/envs/dataspeech/lib:/usr/local/cuda/lib64
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
CONDA_EXE=/Work21/2023/myname/anaconda3/bin/conda
CUDAROOT=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
TMUX=/Work21/2023/myname/test_tmp/tmux-43268/default,133149,3
_CE_CONDA=
MAIL=/var/spool/mail/myname
PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/bin:/Work21/2023/myname/git-2.44.0/bin:/Work21/2023/myname/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/2023/myname/.local/bin:/home/2023/myname/bin:/home/2023/myname/.local/bin:/home/2023/myname/bin
GSETTINGS_SCHEMA_DIR=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/share/glib-2.0/schemas
XML_CATALOG_FILES=file:///Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/etc/xml/catalog file:///etc/xml/catalog
CONDA_PREFIX=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
PWD=/Work21/2023/myname/Voice-Privacy-Challenge-2024
LANG=en_US.UTF-8
TMUX_PANE=%3
SELINUX_LEVEL_REQUESTED=
https_proxy=172.23.166.229:7897
HISTCONTROL=ignoredups
_CE_M=
HOME=/home/2023/myname
SHLVL=3
XDG_CACHE_HOME=/Work21/2023/myname/cache/
CONDA_PYTHON_EXE=/Work21/2023/myname/anaconda3/bin/python
LOGNAME=myname
SSH_CONNECTION=10.10.10.1 58398 10.10.10.41 22
CONDA_DEFAULT_ENV=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/43268
_=/usr/bin/env
PyTorch path: ['/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/python3.11/site-packages/torch']
PyTorch version: 2.0.1+cu117
Using config: configs/anon_sttts.yaml
Using GPUs: 2
2024-12-10 23:45:57,106 - __main__- INFO - Running pipeline: sttts
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
./02_run.sh: line 50: 77247 Aborted                 python run_anonymization.py --config ${anon_config} ${force_compute}
```

**Comment by kbfz12** [comment]
The error occurs even after I set the environment variables CONDA_EXE and CONDA_PYTHON_EXE in env.sh.
stack-trace:
```
[myname@game Voice-Privacy-Challenge-2024]$ ./02_run.sh configs/anon_sttts.yaml 2
AUTOJUMP_ERROR_PATH=/home/2023/myname/.local/share/autojump/errors.log
XDG_SESSION_ID=914
HOSTNAME=game
SELINUX_ROLE_REQUESTED=
PIP_REQUIRE_VIRTUALENV=false
AUTOJUMP_SOURCED=1
SHELL=/bin/bash
TERM=screen
HISTSIZE=1000
SSH_CLIENT=10.10.10.7 32820 22
TMPDIR=/Work21/2023/myname/test_tmp/
CONDA_SHLVL=1
CONDA_PROMPT_MODIFIER=(/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv) 
SELINUX_USE_CURRENT_RANGE=
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
SSH_TTY=/dev/pts/10
USER=myname
http_proxy=172.23.166.229:7897
LD_LIBRARY_PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/:/Work21/2023/myname/anaconda3/envs/dataspeech/lib:/usr/local/cuda/lib64
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
CONDA_EXE=/Work21/2023/myname/anaconda3/bin/conda
CUDAROOT=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
TMUX=/Work21/2023/myname/test_tmp/tmux-43268/default,133149,3
_CE_CONDA=
MAIL=/var/spool/mail/myname
PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/bin:/Work21/2023/myname/git-2.44.0/bin:/Work21/2023/myname/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/2023/myname/.local/bin:/home/2023/myname/bin:/home/2023/myname/.local/bin:/home/2023/myname/bin
GSETTINGS_SCHEMA_DIR=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/share/glib-2.0/schemas
XML_CATALOG_FILES=file:///Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/etc/xml/catalog file:///etc/xml/catalog
CONDA_PREFIX=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
PWD=/Work21/2023/myname/Voice-Privacy-Challenge-2024
LANG=en_US.UTF-8
TMUX_PANE=%3
SELINUX_LEVEL_REQUESTED=
https_proxy=172.23.166.229:7897
HISTCONTROL=ignoredups
_CE_M=
HOME=/home/2023/myname
SHLVL=3
XDG_CACHE_HOME=/Work21/2023/myname/cache/
CONDA_PYTHON_EXE=/Work21/2023/myname/anaconda3/bin/python
XDG_SESSION_ID=914
HOSTNAME=game
SELINUX_ROLE_REQUESTED=
PIP_REQUIRE_VIRTUALENV=false
AUTOJUMP_SOURCED=1
SHELL=/bin/bash
TERM=screen
HISTSIZE=1000
SSH_CLIENT=10.10.10.7 32820 22
TMPDIR=/Work21/2023/myname/test_tmp/
CONDA_SHLVL=1
CONDA_PROMPT_MODIFIER=(/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv) 
SELINUX_USE_CURRENT_RANGE=
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
SSH_TTY=/dev/pts/10
USER=myname
http_proxy=172.23.166.229:7897
LD_LIBRARY_PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/:/Work21/2023/myname/anaconda3/envs/dataspeech/lib:/usr/local/cuda/lib64
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
CONDA_EXE=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/bin/cuda
CUDAROOT=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
TMUX=/Work21/2023/myname/test_tmp/tmux-43268/default,133149,3
_CE_CONDA=
MAIL=/var/spool/mail/myname
PATH=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/bin:/Work21/2023/myname/git-2.44.0/bin:/Work21/2023/myname/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/2023/myname/.local/bin:/home/2023/myname/bin:/home/2023/myname/.local/bin:/home/2023/myname/bin
GSETTINGS_SCHEMA_DIR=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/share/glib-2.0/schemasXML_CATALOG_FILES=file:///Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/etc/xml/catalog file:///etc/xml/catalogCONDA_PREFIX=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venvPWD=/Work21/2023/myname/Voice-Privacy-Challenge-2024LANG=en_US.UTF-8TMUX_PANE=%3SELINUX_LEVEL_REQUESTED=https_proxy=172.23.166.229:7897
HISTCONTROL=ignoredups
_CE_M=
HOME=/home/2023/myname
SHLVL=3
XDG_CACHE_HOME=/Work21/2023/myname/cache/
CONDA_PYTHON_EXE=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/bin/pythonLOGNAME=myname
SSH_CONNECTION=10.10.10.1 58398 10.10.10.41 22
CONDA_DEFAULT_ENV=/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/43268
_=/usr/bin/env
PyTorch path: ['/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/python3.11/site-packages/torch']
PyTorch version: 2.0.1+cu117
Using config: configs/anon_sttts.yaml
Using GPUs: 2
2024-12-10 23:51:12,000 - __main__- INFO - Running pipeline: sttts
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
./02_run.sh: line 50: 80383 Aborted                 python run_anonymization.py --config ${anon_config} ${force_compute}
```

**Comment by pchampio** [comment]
Could you identify the line of https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/blob/main/anonymization/pipelines/sttts/sttts_pipeline.py that cause this issue.
It is very complicated to debug your issue.

PyTorch version: 2.0.1+cu117
So cuda version 11.7, I dont know why it asks for cuda 12.

**Comment by pchampio** [comment]
Is your nvidia driver and graphic card compatible with cuda 11 ?

**Comment by kbfz12** [comment]
Here's the output of `nvidia-smi`:
```
NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4
```
Generally speaking, it should be compatible with CUDA 11.

**Comment by pchampio** [comment]
nvidia-smi CUDA = 12.4. 
I would prefer to see CUDA 11.
But I think nvidia-smi  always output the latest cuda version installed in the system.

**Comment by kbfz12** [comment]
stack-trace that I run the program mannually:
```
(/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv) [myname@gpu06 Voice-Privacy-Challenge-2024]$ python run_anonymization.py --config configs/anon_sttts.yaml
CUDA_VISIBLE_DEVICES: 0
2024-12-11 22:04:53,423 - __main__- INFO - Running pipeline: sttts
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
Aborted (core dumped)
```
So I can only manually test each line using print statements.  It seems that error occurs at line 60 in sttts_pipeline.py.

**Comment by pchampio** [comment]
Just to be sure, before line 60 in sttts_pipeline.py, what is the `print(torch.__version__); print(torch.__path__)` ?
Sorry for the small steps, I have very little clue on how to solve your issue.
I think there is a way to get the full stack trace in pytorch with `export TORCH_SHOW_CPP_STACKTRACES=1`.

Some related similar-ish issues: https://github.com/pytorch/pytorch/issues/51080, https://github.com/pytorch/pytorch/issues/88882

**Comment by kbfz12** [comment]
I haven’t resolved the previously mentioned issue yet, but I noticed another potential problem when passing gpu_ids as arguments to anonymization.py. For example:
`python run_anonymization.py --config configs/anon_sttts.yaml --gpu_ids 4,5`
This could cause errors because in run_anonymization.py, CUDA_VISIBLE_DEVICES is already set at line 13, but at line 41 it still uses the original indices. I temporarily fixed this issue by modifying line 40 to:
`for gpu in range(len(gpus)):`
This resolved the problem for now.

Additionally, I managed to set the TORCH_SHOW_CPP_STACKTRACES environment variable successfully in the code, but I still didn’t get the full stack trace.

**Comment by kbfz12** [comment]
Here’s the torch.__version__ and torch.__path__, as well as the stack trace, captured before line 60 in sttts_pipeline.py:
```
(/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv) [myname@game Voice-Privacy-Challenge-2024]$ python run_anonymization.py --config configs/anon_sttts.yaml --gpu_ids 4,5
CUDA_VISIBLE_DEVICES: 4,5
2024-12-23 03:12:42,803 - __main__ - INFO - Running pipeline: sttts
2.0.1+cu117
['/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/python3.11/site-packages/torch']
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
Aborted
```
It seems that the settings look fine, but the issue still persists.

**Comment by kbfz12** [comment]
After a long debugging process, I’ve temporarily solved the issue. It seems the problem was in the env.sh file. When `source env.sh`, it was adding other CUDA library paths to the LD_LIBRARY_PATH in addition to the specified venv environment for the competition, which caused the library file error. After modifying the env.sh to ensure that the competition environment is the only one specified in LD_LIBRARY_PATH, the issue was resolved.

Thank you so much for your help throughout this process!

**Comment by pchampio** [comment]
Glad you managed to fix the issue, I didn't think that the values after `/Work21/2023/myname/Voice-Privacy-Challenge-2024/venv/lib/` would matter in the `LD_LIBRARY_PATH`.
Good to know.
